kind: pipeline
name: example-pipeline

steps:
 - name: build
   image: node:latest
   commands:
   - npm install
   - npm run test
   when:
   branch:
   - master
   event:
   - push
   - pull-request